spring:
  profiles:
    active: local # 기본 환경 선택

server:
  port: 8081

---
spring:
  profiles: local
dynamodb:
  endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  region: ap-northeast-2

---
spring:
  profiles: dev
dynamodb:
  endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  region: ap-northeast-2

---
spring:
  profiles: test

dynamodb:
  endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  region: ap-northeast-2

